### ISSUE TITLE
wrong repo

### ISSUE THREAD

**Issue by hone-zaun** [sajidali007522/edu#18]
@sajidali007522 Please ignore this commit: https://github.com/sajidali007522/edu/commit/c2094cda1e556b833b0ea305f498488f8115ff0b

This file was used for an internal test to check how it would look like full-width.

Spoiler: not that good! :smile: 

Shouldn't have been commited here. Sry!

**Comment by sajidali007522** [comment]
@hone-zaun  no problem
I am just going to start work and will let you know to test all changes.

**Comment by hone-zaun** [comment]
@sajidali007522 Great! Thank you
